"""Noise-coverage table (T3): share of documents in HDBSCAN's noise cluster.

A model could look coherent by sending hard documents to the noise cluster,
so the appendix reports, for each HDBSCAN-based model and dataset, the share
of documents left as noise: mean and standard deviation over the runs (3
seeds x 5 requested topic counts).
"""

from __future__ import annotations

import polars as pl

from src.comparisons.analysis import BENCHMARK_DATASETS, REQUESTED_TOPICS
from src.paper_benchmark import model_runs, standard_runs
from src.paper_outputs import (
    DATASET_LABELS,
    HDBSCAN_VARIANTS,
    PRELIMINARY_NOTE,
    _latex_escape,
    paper_label,
)

NOISE_MODELS = ("baseline", *HDBSCAN_VARIANTS)


def noise_coverage(results: pl.DataFrame, models=NOISE_MODELS) -> pl.DataFrame:
    """Noise share (% of documents) per model and dataset, over its runs.

    `Complete` is true when every seed has all requested topic counts.
    """
    standard = standard_runs(results)
    rows = []
    for model in models:
        for dataset in BENCHMARK_DATASETS:
            runs = model_runs(standard, model, dataset).with_columns(
                (
                    pl.col("outliers").cast(pl.Float64, strict=False)
                    / pl.col("n_observations").cast(pl.Float64, strict=False)
                    * 100
                ).alias("noise")
            )
            noise = runs["noise"].drop_nulls()
            if noise.is_empty():
                continue
            rows.append(
                {
                    "Model ID": model,
                    "Dataset": dataset,
                    "Runs": noise.len(),
                    "Complete": noise.len()
                    == runs["seed"].n_unique() * len(REQUESTED_TOPICS),
                    "Noise mean": noise.mean(),
                    "Noise SD": noise.std() if noise.len() > 1 else 0.0,
                }
            )
    return pl.DataFrame(rows, infer_schema_length=None) if rows else pl.DataFrame()


def _cell(row: dict | None) -> str:
    if row is None:
        return "--"
    text = rf"{row['Noise mean']:.1f}\,{{\scriptsize$\pm${row['Noise SD']:.1f}}}"
    return text if row["Complete"] else text + r"$^\dagger$"


def noise_table_latex(
    coverage: pl.DataFrame,
    catalog: dict,
    models=NOISE_MODELS,
    preliminary: bool = False,
    label: str = "tab:noise_coverage",
    note: str = "",
) -> str:
    """Booktabs `table*`: models x datasets, plus the mean over datasets."""
    cells = {(r["Model ID"], r["Dataset"]): r for r in coverage.to_dicts()}
    header = " & ".join(
        [r"\textbf{Model}"] + [DATASET_LABELS[d] for d in BENCHMARK_DATASETS] + ["Mean"]
    )
    body, partial = [], False
    for model in models:
        row_cells = [cells.get((model, d)) for d in BENCHMARK_DATASETS]
        if not any(row_cells):
            continue
        partial = partial or any(c and not c["Complete"] for c in row_cells)
        present = [c["Noise mean"] for c in row_cells if c]
        mean = sum(present) / len(present)
        mean_text = f"{mean:.1f}" + (
            "" if len(present) == len(BENCHMARK_DATASETS) else r"$^\ddagger$"
        )
        body.append(
            " & ".join(
                [paper_label(model, catalog)]
                + [_cell(c) for c in row_cells]
                + [mean_text]
            )
            + r" \\"
        )
        if model == models[0]:
            body.append(r"\midrule")
    caption = (
        r"Share of documents assigned to the HDBSCAN noise cluster (\%), mean "
        r"$\pm$ standard deviation over 3 seeds $\times$ 5 requested topic "
        r"counts. Mean: average over the datasets with runs."
    )
    if any("ddagger" in line for line in body):
        caption += r" $^\ddagger$Over fewer datasets."
    if partial:
        caption += r" $^\dagger$Incomplete runs."
    if note:
        caption += " " + _latex_escape(note)
    if preliminary:
        caption += r" \textbf{Preliminary.}"
    lines = [
        "% Generated by scripts/analysis/make_paper_outputs.py",
        *([f"% {PRELIMINARY_NOTE}"] if preliminary else []),
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        rf"\begin{{tabular}}{{l{'r' * (len(BENCHMARK_DATASETS) + 1)}}}",
        r"\toprule",
        header + r" \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\end{table*}",
    ]
    return "\n".join(lines) + "\n"
